name: farm-manager
region: nyc
services:
  - name: farm-manager
    github:
      repo: alisjj/Farm-Manager
      branch: main
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: DB_DIALECT
        value: postgres
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_NAME
        value: ${db.DATABASE}
      - key: DB_USER
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
      - key: JWT_SECRET
        value: ${jwt-secret}
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 8080
databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
